In [1]:
import pandas as pd

In [3]:
medical = pd.read_csv("insurance.csv")
medical

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [4]:
import plotly.express as px
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

sns.set_style('darkgrid')
matplotlib.rcParams['font.size'] = 14
matplotlib.rcParams['figure.figsize'] = (10, 6)
matplotlib.rcParams['figure.facecolor'] = '#00000000'

In [8]:
fig = px.histogram(medical, x="age", nbins=30, title="Distribution of Age")
fig.update_layout(bargap=0.1)
fig.show()

In [10]:
fig = px.histogram(medical, x="bmi", nbins=30, title="Distribution of Age")
fig.update_layout(bargap=0.1)
fig.show()

In [16]:
fig = px.histogram(medical, x="age", color="charges", title="Distribution of Age")
fig.update_layout(bargap=0.1)
fig.show()

In [19]:
fig = px.histogram(medical, x="charges", color="smoker", title="Distribution of Age")
fig.update_layout(bargap=0.1)
fig.show()

In [17]:
medical.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [22]:
cor = medical.corr(numeric_only=True)
cor

               age       bmi  children   charges
age       1.000000  0.109272  0.042469  0.299008
bmi       0.109272  1.000000  0.012759  0.198341
children  0.042469  0.012759  1.000000  0.067998
charges   0.299008  0.198341  0.067998  1.000000